#!/usr/bin/env python

import rospy
import numpy as np

from geometry_msgs.msg import Twist, Point, Pose
from sensor_msgs.msg import LaserScan
from nav_msgs.msg import Odometry
from std_srvs.srv import Empty

def talker():
   pub_cmd_vel = rospy.Publisher('cmd_vel', Twist, queue_size=10)
   #rospy.init_node('cmd_vel', anonymous=True)
   rate = rospy.Rate(10) # 10hz
   while not rospy.is_shutdown():
    vel_cmd = Twist()
    vel_cmd.linear.x = 0.15
    vel_cmd.angular.z = 0.0
    pub_cmd_vel.publish(vel_cmd)
    print("velocity: 0.15, angle: 0.0")
    rate.sleep()

if __name__ == '__main__':
    print("starting")
    rospy.init_node('Husky_dqn')
    try:
        talker()
    except rospy.ROSInterruptException:
        pass